version: "3"

# 
services:

    db:
        image: postgres
        container_name: api_pg
        environment: 
            - POSTGRES_DB=api
            - POSTGRES_USER=sa
            - POSTGRES_PASSWORD=1111
        ports: 
            - 5432:5432

    redis:
        image: redis
        restart: always
        container_name: api_rd
        ports: 
            - 6379:6379
    